# Generated by Django 3.0.3 on 2020-04-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='embedding',
            table='embeddings',
        ),
    ]
